### ISSUE TITLE
Not an issue ; just an expression of gratitude

### ISSUE THREAD

**Issue by YoshiMitaka** [rzhou1999/woosticker#1] opened 2021-04-08 19:57 UTC
So I've been looking for a way to send emojis on a discord chat without nitro. That would mean either using server emojis or Samsung keyboard/ gboard emojis. After hours of hunting all I could find was third-party apps on Google play that just transferred PNG files/ convert to PNG  to serve as a sticker pack in WhatsApp. Then I came across usticker and later some obscure play store app but sadly they were no longer compatible with the latest version of gboard. I happened to stumble across a discussion #49 if I remember correctly and came to this bad boy. I am delighted to inform that though it may be minimalist it does the job perfectly and serves as its own keyboard eliminating dependency on gboard updates and whatever in the future. Mad props for this project. Even in its primitive form it delivers in a way that cannot be impeded by any other software or OS update. Thank you. I am surprised that you're the first one to have actually thought of and enacted this amazing notion. The fact that it is so easy to switch between keyboards is wonderful and surpasses everything uSticker stood for. I hope to see this app in the best of form one day in the play store. Thank you for this simple yet ingenious application! 
Regards,
Yoshi

**Comment by YoshiMitaka** [comment] 2021-04-08 20:00
One thing that you should work on though is the fact that the app considers every image in folder location as a sticker just like uSticker . It is definitely annoying for functionality. If I were to invest in developing this I would allow for selection of images rather than automatically include all in the keyboard. Also if it appeals, you could rename this to mojiboard(personal preference) in the future. Thanks

**Comment by YoshiMitaka** [comment] 2021-04-08 20:07
Also every time I download a new image to serve as a sticker I have to run the directory again and allow permission. I would prefer if there is an option of adding and selecting rather than scanning entirely. Ps. Mojiboard sound even catchier

**Comment by rzhou1999** [comment] 2021-04-08 20:49
Appreciate the kind words. Technically there have been a couple of projects related to image keyboards before this that I'm deeply indebted to (google released a sample application which was very helpful) and google could pull support for the commit content API just like they did with gboard, but thankfully they haven't indicated that this is a possibility in any way yet.

> One thing that you should work on though is the fact that the app considers every image in folder location as a sticker just like uSticker . It is definitely annoying for functionality.

Hmm, could you speak a little more about this? If you're referring to how all pictures are scraped from the selected directory, I decided to emulate uSticker because I found it much easier in my experience to "make" sticker packs on a computer and then transfer to my phone than compiling them completely on Android (honestly mobile as a computing environment just isn't ready for file management). My usage pattern is to make a directory specifically for woosticker-- I also have 300+ stickers loaded in at any point in time, and selecting each one individually would be incredibly time consuming. Do you have any ideas on what this feature might look like?

> Also every time I download a new image to serve as a sticker I have to run the directory again and allow permission. I would prefer if there is an option of adding and selecting rather than scanning entirely.

Hm, if you mean that there's an option where you can add individual images (rather than replace the entire directory, which is what woosticker currently does), that might be interesting to add and should be doable. I'll look into it when/if I have time.

>Also if it appeals, you could rename this to mojiboard(personal preference) in the future.

As for the name, to be honest I'm a little partial to woosticker if only because it pays homage to uSticker. I only got inspired to do this because apsun mentioned it in a passing comment, so it feels only fair to acknowledge the app's source. If multiple people have strong feelings about it though then I'm open to reconsidering :).

**Comment by YoshiMitaka** [comment] 2021-04-09 08:57
So it was emulated. That is understandable but to really I would say harness functionality of an apk the app should be tied solely to a smartphone but that is just a personal sentiment. If you do however feel that importing from a pc should also be an added bonus I would suggest an option in a developed UI that specifically mentions "import stickers from a personal computer" or something similar while connected with a USB port. I reckon the option for choosing a folder in mobile and selecting which PNG files from the entire folder (downloads in this case ) are to be chosen in conjunction with a select all option would be more viable. I am not aware as of now of any way you can create a separate folder for stickers/PNGs as downloads is the most convenient. Here are a few things in a nutshell as writing them down in prose is going to be a hassle:

1. A more polished UI. Perhaps a logo for your app. A kawaii one would be a good match as that's what stickers are mostly about.
2. A startup animation featuring the mascot chosen as the app image. Simpler the better witch a catchy tune.
3. App should direct user to the main interface after that which in later stages should contain options of converting standard images to a no-background PNG . First it should prompt settings to keyboard and file access to get the app started. Then give options for creating stickers or find stickers. It can't get any simpler. Two subdivisions for browse would be phone and desktop. Open folder and an option to select all in a particular directory.
Once stickers are added the mascot should guide into opening the keyboard. 

About the name issue. I don't think you will be able to retain it. There is another project based on the same name in GitHub and it definitely doesn't sound original. You should understand that all works are intentionally or unintentionally based upon inspirations or past experiences we draw from the word. Even original concepts are derivations from how our thought process is shaped throughout our lives by imitating what we see. If you are so dead set on insisting that uSticker was solely responsible for this project despite there being several who have embraced it before, you can always put their name in the credits section of the app(also I don't know how woosticker is reminiscent of uSticker). I would definitely recommend letting your imagination run wild or ask for suggestions or help from others. And update: mojiboard and mojiboard sound banal. You should go for stickIT or something even more creative but alas all of that depends on intiative and how much soul one is willing to put into a project or creation. I do hope to see what you make out of it. 
Cheers and good luck!

**Comment by rzhou1999** [comment] 2021-04-09 19:30
I think we might have differing use cases here-- I never intended woosticker to be a add-stickers-one-by-one discord nitro replacement so doing what you propose for my use case would be nigh impossible-- again, I have dozens of "packs" and hundreds of stickers to manually choose, and this app exists solely because some apps (looking at you Threema) don't support custom stickers natively at all. If woosticker happens to work as a discord nitro replacement then I won't make it intentionally harder, but I'd also suggest people look into just supporting the company and subscribing nitro lol. I believe being a last-ditch alternative for Threema/XMPP/MMS/etc. sticker support was the general intention for uSticker/Stickerboard as well, so the base functionality likely won't change.

I do agree that adding optional support for one-by-one selection would be helpful, but ultimately I wouldn't want it to replace the existing logic since I think that the current UX (barring the graphics) already is emblematic of what I think app design should be (i.e. only app-internal deliberate actions affect keyboard state, very clear and attributable in terms of which pack/source each sticker comes from, etc.). If you feel strongly about this, anyone is welcome to fork and modify some of the filesystem logic (I haven't had time to set up a license just yet, but it'll probably be something like MIT or whatever some of the 3rd party libraries I used allow me to do).

Lastly, I am unaware of a different project on github that uses "woosticker" exactly-- the only relevant one I can find is from an abandoned project titled "WOO Stickers", so I believe I should be in the clear. If anything, I might only re-stylize to "wooSticker" to make the connection more obvious (and you're right that other projects did inspire this one, but uSticker undeniably was the most influential. apsun has also let me know that I can take some of their UI elements, so the attribution is only made more pressing by that). Also, I'd like you to understand that truthfully I don't really care about attracting uses through a catchy name or something-- I built this app solely because I wanted to use it. People who want a uSticker replacement or uSticker functionality will come, and I'm not sure I need to be marketing to others.

**Comment by YoshiMitaka** [comment] 2021-04-10 09:11
That is exactly why I expressed everything as a "personal sentiment". However, I'm am no longer going to pressure anyone to make any changes.  You get your stickers in one place , I get to use it on discord or anywhere I find a use and I thank you for making it easier for everyone. It's clearly a win-win for the both of us. The app is usable and delivers exactly as intended. End of story. I only wanted to help you out with more promising features. I have been analysing software usage for years and will learn development in the recent one or two years. I completely understand if you donot want to receive any assistance or help regarding the app development and just intend it for uSticker fans. The fact that I may have pushed you to improving the app or making them available to the masses to get wider feedback and improving of ones skillset was just a kind gesture as a fellow dev but apparently one cannot expect it to be appreciated. I often confuse my methods with others' and I am sorry for that. I was just expressing what I would have done if it were my project(like putting it for public , gathering feedback, improving , prototyping...) and I clearly was wrong to do so. And please donot make any assumptions about me if I don't use discord nitro when you donot know the full story like you probably didn't buy winrar(which even I didn't but know that it is exactly what the dev intends).Note that discord does not own any emojis, stickers or GIFs. It doesn't even have the rights to using these images or looped animations but fans appreciating meme culture do it for the community and don't press charges. Nitro is technically illegal as they are earning money off the hardwork of other individuals who just aren't interested in defending their rights. About supporting the Devs; any business is driven by entirely selfish concerns. They donot want to contribute to the community or want to help you. All they want is money that is the primary objective of any business. That is not to say that selfless people donot exist in the world but they're negligible and are often obscure and have no authority. I am all for supporting Devs that are true to their promises, struggling to find balance and genuinely care about their consumers beyond paying them for the services they already provide(like no man's sky) but for large corporations/cash cows that build inconvenience and then offer solutions for it for a price. I would rather let the other mindless consumers pay for that typically the ones going: support the Devs hahaha.
Lastly, I don't use this app as a means of cheating nitro. I use it to send emojis / stickers that I want to share with others regardless of their presence in other servers and so far I haven't actually used it as a substitute for an emoji from another server. I find them over the internet , create stickers myself from characters I love and I have every right to use them at will whether discord likes it or not. They're the ones stripping our rights and asking us to pay for it and that is none of my concern if I don't let them have their way. Even if I use an emoji from a particular server please keep in mind neither discord or that servers owns the rights to that and the person that does intends it to be used freely. The process is as similar and legal to using gboards stickers in the chat. The only thing that does change is that I use my stickers whether I found them over the internet or another server. This conversation is pointless and is leading to nowhere and I would appreciate if you don't start it again



What I actually came here for is to ask a question about functionality.

How do I use the keyboard on desktop. Do I emulate it using blue stacks?  And once I've emulated it, will it work only in other emulated chats meaning I will have to use discord app emulated as well or some similar platform like WhatsApp or can i somehow use to directly on my desktop the keyboard that is containing the emojis/stickers

**Comment by rzhou1999** [comment] 2021-04-10 16:30
For the record, I don't use winrar at all so your point is kind of moot-- 7zip is open source and free :). As for the discord issue, I don't see what the issue is with supporting both discord and the artists that originally create the work-- you are indeed using discord as a service, and they have the right to ask for payment if one wants to use parts of that service, no? I'm all for some anarchism, but complaining that you want a paid service but at the same time don't want to pay for that service is a bit rich. Similarly, you are using others' artwork, so it would similarly be only right to support them (just as I myself have done and even recommend on this repo's readme). Sure, licensing may not transfer in full, but if you want to play that game then quite frankly it's impossible to reconcile woosticker/usticker/etc. with that on a fundamental level I'd argue. On the contrary to what you've said, I think you're the one who latched onto but one of multiple reasons why I won't rewrite my app's core functionality to accommodate a use case that I personally don't even agree with, and is yourself insisting on continuing a self-admitted "pointless" conversation under the guise of "advice". For what it's worth, I agree with this being a pointless conversation so I'm closing this issue...

**Closed as completed by rzhou1999** 2021-04-10 16:30 UTC
